### ISSUE TITLE
Calls in Q, but no ringing...

### ISSUE THREAD

**Issue by seabreen** [iAnomaly/OpenVBX-ACD#1]
Hi iAnomaly!

I love your Plugin for OpenVBX! -- only problem is I can't seem to get an incoming call to ring anyplace. I can see it in the Call Queue screen, but devices and browser clients, sit idle.

Any ideas?

Chris

**Comment by iAnomaly** [comment]
Hi Chris, thanks for the feedback! There are some bugs that still need to be squashed. When you are at the Queue screen, if you add ?dbg=agents to the URL in your browser and hit enter, what does that screen say?

**Comment by seabreen** [comment]
Hi Cameron!

Here's what came up for the debug: 

array(1) { ["U1"]=> string(34) "CAf4f1f4182f184c8c8479c25f140f9326" }

Additionally, when logged in and set to Available, I'm getting this strange entry (Screenshot attached).

Thanks Cameron! Hope you're having a great night! :)

Let me know if I can help in any other way!

Chris

**Comment by iAnomaly** [comment]
OK. So the quick fix is to set yourself Unavailable the Available again. Also please be sure you're using the newer Twilio API (2010-04-01). Let me know if you don't know what that is or where to find it.

Assuming you are already on the newer API, I haven't had a chance to nail down why this happens so if you want to figure out how to recreate it, I can patch it.

P.S. I didn't see the screenshot you mentioned.

Thanks,
Cameron

**Comment by seabreen** [comment]
Hi Cameron,

I set myself as Unavailable and Available again, but no luck. Currently using Twillio API 2010-04-01, when I come back as "Available" I'm getting his:

<table id="table-queue" class="vbx-items-grid">
    <thead class="items-head">
      <tr>
        <th>Queue</th>
        <th>Caller</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>ZIP</th>
        <th>Wait</th>
      </tr>
    </thead>
    <tbody id="table-queue-body" class="items-row"><tr></tr><td>undefined</td><td>undefined</td><td>undefined</td><td>undefined</td><td>undefined</td><td>undefined</td><td>NaN:NaN</td></tbody>
  </table>


Hope that makes it clearer, let me know if you want me to test anything!

Thanks Cameron!

**Comment by iAnomaly** [comment]
Hi Chris, not sure how a "null" call got on the queue, but that's what's
causing your troubles. When you are at the Queue page, please append
"?dbg=delCalls" to the URL and hit enter. That will clear out the queue and
you should be able to receive calls again. See if you can figure out what
you did to get a "null/undefined" call on there too.

Hope this helps!

On Tue, Jan 24, 2012 at 8:42 PM, seabreen <
reply@reply.github.com

**Comment by bondarewicz** [comment]
Hi Cameron, did you ever look into issue#2?

**Comment by iAnomaly** [comment]
No, unfortunately I haven't looked at this code in over a year.
