### ISSUE TITLE
calls are not Queuing 

### ISSUE THREAD

**Issue by imehesz** [iAnomaly/OpenVBX-ACD#2]
hello,

I'm new to OpenVBX and trying to setup this ACD Queue plugin.

I might be setting up the Flow wrong, but the CALL never actually makes to the Queue (can't see it in the queue list, no on-hold music, nothing). 
If I add a "GREETING" VApplet in the "When no agents are accepting calls..." box, it rings-rings for about 10-15 seconds (I'd assume I should hear the HOLD music by now) - and then it plays the GREETING and HANGS UP.

**My Flow looks like this:**
When call is coming in: GREETING -> 
MENU (press: 1,2,3 etc) -> 
PRESS #1 DIAL Sales GROUP, IF nobody answers Go To: Queue -> 
Queue Name: Some Queue Name, Music: Ambient, When no agents are accepting calls: GREETNIG

thanks,
--iM

**Comment by bondarewicz** [comment]
Did you ever got this resolved?

**Comment by iAnomaly** [comment]
Hi Imre,

If you aren't setting yourself as "Available" in the Queue section the flow is going to proceed to whatever you set for the "When no agents are accepting calls..." section. In your example above, it plays the greeting and hangs up since that's the last widget in the flow.

Could you PM me the URL you are testing on with a throw away account? I'll take a look if you'd like.

Cheers,
Cameron

**Comment by olea555** [comment]
I ran into the same problem and was completely confused by the set yourself to Available as I did not see that anywhere. Before I started testing this Queue plugin I had been testing another Queue plugin: OpenVBX-Plugin-Queue-master

It appears that they conflict. It wasn't until I removed the OpenVBX-Plugin-Queue-master pluging that I was able to see the Queue differently with the Available option etc..

**Comment by jasonwinget** [comment]
I am having issues with getting this to work as well.  I did notice that you cannot have a space in the queue name when you test the API in the Twillio API tester.  However, the problem I am having there is that calls ring through and after 30 seconds they just drop to a voicemail prompt. It doesn't see like any queue is actually happening.  One hint is no music, I hear ring down instead.

**Comment by DODOM2** [comment]
Anybody have a solution to this yet?
